### ISSUE TITLE
Runner does not auto enable

### ISSUE THREAD

**Issue by Shmeeb** [SimonFlash/TriviaQuest#1]
runner also does not enable on startup despite 
`enable-on-startup=true`

tq ver 2.0.1

    Minecraft: 1.10.2
    SpongeAPI: 5.2.0-SNAPSHOT-c675e80
    SpongeForge: 1.10.2-2477-5.2.0-BETA-2793
    Minecraft Forge: 12.18.3.2488

**Comment by SimonFlash** [comment]
Addressed by v2.1.1
